import { Albums } from './album.model';

export let ALBUMS: Album[] = [

    new Album('Cameosis', 'Cameo', 'Cameosis is the fifth album by the funk/soul band Cameo, released in 1980.'),
    new Album('Alligator Woman', 'Cameo', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Machismo', 'Cameo', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Honey', 'Ohio Players', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Pleasure', 'Ohio Players', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Pain', 'Ohio Players', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Your Wish is My Comman', 'Lakeside', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Fantastic Voyage', 'Lakeside', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Keep On Moving Straight Ahead', 'Lakeside', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Kind of Blue', 'Myles Davis', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('In a Silent Way', 'Myles Davis', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Milestones', 'Myles Davis', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('A Love Supreme', 'John Coltraine', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Giant Steps', 'John Coltraine', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Blue Train', 'John Coltraine', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Ella and Louis', 'Louis Armstrong', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Ambassador Satch', 'Louis Armstrong', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('The Very Best of', 'Louis Armstrong', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Thriller', 'Michael Jackson', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('History', 'Michael Jackson', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Off the Wall', 'Michael Jackson', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Artpop', 'Lady Gaga', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Joanne', 'Lady Gaga', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('The Fame', 'Lady Gaga', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Girl', 'Pharrel', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('In My Mind', 'Pharrel', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),
    new Album('Pink Slime', 'Pharrel', 'Something about this album which is unique listed here because this is so interesting and people want to know everything about it without mindeding this long eloquent qwell-written sentence without punctuation about this artist and music and genre and album especially'),




]
